### ISSUE TITLE
saya punya link referensi CTF lagi barangkali mau di tambahin

### ISSUE THREAD

**Issue by tanwirulqulub999** [agussetyar/awesome-reference#11]
pada referensi CTF barangkali mau ditambahin, link pada berikut ini :
- https://yohan.es/ctf/
- https://blog.compactbyte.com/
terima kasih.

**Comment by agussetyar** [comment]
bukan disini tempatnya

**Comment by tanwirulqulub999** [comment]
wkwkwk sorry gus gue ngga teralalu pandai github jadinya gini maklum wkwkwk

**Comment by tanwirulqulub999** [comment]
di pull request kah?
